### ISSUE TITLE
除express以外都在本地部署好了，浏览器上登录之后多点几下就会有如下报错，请帮我看一下是什么，谢谢

### ISSUE THREAD

**Issue by baosha45818** [teashirtt/resume-analysis-system#5]
Uncaught runtime errors:
×
ERROR
e.createTime.split is not a function
TypeError: e.createTime.split is not a function
    at eval (webpack-internal:///./node_modules/unplugin/dist/webpack/loaders/transform.js?unpluginName=unplugin-vue-components!./node_modules/unplugin/dist/webpack/loaders/transform.js?unpluginName=unplugin-auto-import!./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[5]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/user/uploadResume.vue?vue&type=template&id=4b4d671c&scoped=true:83:198)
    at renderFnWithContext (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:886:13)
    at renderSlot (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:2753:53)
    at eval (webpack-internal:///./node_modules/element-plus/es/components/col/src/col2.mjs:74:117)
    at renderFnWithContext (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:886:13)
    at normalizeChildren (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6470:34)
    at createBaseVNode (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6289:5)
    at _createVNode (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6365:10)
    at createVNodeWithArgsTransform (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6238:10)
    at createBlock (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6220:21)

**Comment by baosha45818** [comment]
登录之后，先点个人中心再点简历上传或简历解析还会有：
Uncaught runtime errors:
×
ERROR
Cannot read properties of null (reading 'parentNode')
TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (webpack-internal:///./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js:207:28)
    at ReactiveEffect.componentUpdateFn [as fn] (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5404:9)
    at ReactiveEffect.run (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:217:19)
    at instance.update (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5433:16)
    at callWithErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:328:33)
    at flushJobs (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:517:9)

**Comment by teash1rt** [comment]
全局搜 e.createTime.split 然后调试看下 e.createTime 是不是为空

第二个问题我这周末解决下

**Comment by teash1rt** [comment]
当时没用ts写
所以前端问题可能比较多hhh

**Comment by baosha45818** [comment]
好的万分感谢！
还想请问一下那个后台简历数据中先还有扇形图那些怎么看怎么进入
还有项目文件夹里Utils里format和gather好像我没有用到会不会有影响呢

**Comment by teash1rt** [comment]
> 好的万分感谢！ 还想请问一下那个后台简历数据中先还有扇形图那些怎么看怎么进入 还有项目文件夹里Utils里format和gather好像我没有用到会不会有影响呢

扇形图那些是高级权限（对应用户表中 type=1）的可以查看，可以直接改表或者改下后端超级管理员的邮箱通过前端去升级权限
Utils 只是我开发过程中用的代码，没用到是正常的

**Comment by teash1rt** [comment]
第二个问题没复现出来呀🤔
拉一下代码看看还有没有报错

**Comment by baosha45818** [comment]
非常感谢，问题已经解决了，似乎是前端收到的createTime格式是数组，在前端添加了数组格式转化成时间字符串就没有报错了
